<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hyesop Shin">
<meta name="dcterms.date" content="2026-05-02">
<meta name="keywords" content="spatial interpolation, kriging, generalised additive model, air quality, cross-validation, reproducibility">

<title>aqsurface: Spatial Interpolation Methods for Urban Air Quality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="aqsurface-rjournal_files/libs/clipboard/clipboard.min.js"></script>
<script src="aqsurface-rjournal_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="aqsurface-rjournal_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="aqsurface-rjournal_files/libs/quarto-html/popper.min.js"></script>
<script src="aqsurface-rjournal_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="aqsurface-rjournal_files/libs/quarto-html/anchor.min.js"></script>
<link href="aqsurface-rjournal_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="aqsurface-rjournal_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="aqsurface-rjournal_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="aqsurface-rjournal_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="aqsurface-rjournal_files/libs/bootstrap/bootstrap-8a894fcc3cb5e37eb5bf30def131be2f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#air-pollution-and-population-exposure-in-seoul" id="toc-air-pollution-and-population-exposure-in-seoul" class="nav-link" data-scroll-target="#air-pollution-and-population-exposure-in-seoul">Air pollution and population exposure in Seoul</a></li>
  <li><a href="#a-three-paradigm-framing-of-the-literature" id="toc-a-three-paradigm-framing-of-the-literature" class="nav-link" data-scroll-target="#a-three-paradigm-framing-of-the-literature">A three-paradigm framing of the literature</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#geostatistics-universal-kriging" id="toc-geostatistics-universal-kriging" class="nav-link" data-scroll-target="#geostatistics-universal-kriging">Geostatistics: Universal Kriging</a></li>
  <li><a href="#statistical-inference-generalised-additive-models" id="toc-statistical-inference-generalised-additive-models" class="nav-link" data-scroll-target="#statistical-inference-generalised-additive-models">Statistical inference: Generalised Additive Models</a></li>
  <li><a href="#machine-learning-random-forest" id="toc-machine-learning-random-forest" class="nav-link" data-scroll-target="#machine-learning-random-forest">Machine learning: Random Forest</a></li>
  <li><a href="#road-side-adjustment-via-an-empirical-ratio" id="toc-road-side-adjustment-via-an-empirical-ratio" class="nav-link" data-scroll-target="#road-side-adjustment-via-an-empirical-ratio">Road-side adjustment via an empirical ratio</a></li>
  <li><a href="#three-validation-strategies" id="toc-three-validation-strategies" class="nav-link" data-scroll-target="#three-validation-strategies">Three validation strategies</a></li>
  </ul></li>
  <li><a href="#the-aqsurface-package" id="toc-the-aqsurface-package" class="nav-link" data-scroll-target="#the-aqsurface-package">The aqsurface package</a>
  <ul class="collapse">
  <li><a href="#relation-to-existing-r-packages" id="toc-relation-to-existing-r-packages" class="nav-link" data-scroll-target="#relation-to-existing-r-packages">Relation to existing R packages</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#validation-strategy-a-three-way-decomposition" id="toc-validation-strategy-a-three-way-decomposition" class="nav-link" data-scroll-target="#validation-strategy-a-three-way-decomposition">Validation strategy: a three-way decomposition</a></li>
  <li><a href="#covariate-inclusion-eliminates-the-road-side-bias" id="toc-covariate-inclusion-eliminates-the-road-side-bias" class="nav-link" data-scroll-target="#covariate-inclusion-eliminates-the-road-side-bias">Covariate inclusion eliminates the road-side bias</a></li>
  <li><a href="#speed-where-the-paradigms-separate" id="toc-speed-where-the-paradigms-separate" class="nav-link" data-scroll-target="#speed-where-the-paradigms-separate">Speed: where the paradigms separate</a></li>
  <li><a href="#winter-and-summer-contrasting-two-atmospheric-regimes" id="toc-winter-and-summer-contrasting-two-atmospheric-regimes" class="nav-link" data-scroll-target="#winter-and-summer-contrasting-two-atmospheric-regimes">Winter and summer: contrasting two atmospheric regimes</a></li>
  <li><a href="#what-the-predicted-surfaces-actually-look-like" id="toc-what-the-predicted-surfaces-actually-look-like" class="nav-link" data-scroll-target="#what-the-predicted-surfaces-actually-look-like">What the predicted surfaces actually look like</a></li>
  <li><a href="#where-the-paradigms-disagree-geographically" id="toc-where-the-paradigms-disagree-geographically" class="nav-link" data-scroll-target="#where-the-paradigms-disagree-geographically">Where the paradigms disagree geographically</a></li>
  <li><a href="#paradigm-rmse-distributions-full-sweep" id="toc-paradigm-rmse-distributions-full-sweep" class="nav-link" data-scroll-target="#paradigm-rmse-distributions-full-sweep">Paradigm RMSE distributions, full sweep</a></li>
  <li><a href="#edge-case-pure-nugget-kriging-with-external-drift" id="toc-edge-case-pure-nugget-kriging-with-external-drift" class="nav-link" data-scroll-target="#edge-case-pure-nugget-kriging-with-external-drift">Edge case: pure-nugget kriging with external drift</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements">Acknowledgements</a></li>
  <li><a href="#software-and-code-availability" id="toc-software-and-code-availability" class="nav-link" data-scroll-target="#software-and-code-availability">Software and code availability</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../aqsurface-rjournal.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">aqsurface: Spatial Interpolation Methods for Urban Air Quality</h1>
<p class="subtitle lead">A Speed-Accuracy Comparison of Kriging, GAM, and Random Forest on Seoul’s Monitoring Network</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Hyesop Shin <a href="mailto:hyesop.shin@auckland.ac.nz" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            School of Environment, University of Auckland
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Understanding the association between ambient air pollution and population exposure is a vital precursor for health risk assessment, and spatial interpolation has long been used to estimate concentration fields from a finite number of monitoring stations. However, comparisons across modelling paradigms have remained limited, and the published literature emphasises prediction accuracy in isolation, while computational cost and validation strategy are rarely reported jointly. In addition, the in-sample RMSE that is conventionally reported can be misleading for methods that interpolate exactly, and a systematic underprediction at road-side stations has been observed when models are trained only on background sites. This paper compares Universal Kriging (gstat), Generalised Additive Models (mgcv), and Random Forest (ranger) on a 76-station Seoul air-quality monitoring network for both PM<sub>10</sub> and NO<sub>2</sub>. The three paradigms are evaluated under three validation regimes (in-sample, spatial cross-validation, and a held-out road-side set) and on per-fit wall-clock cost. Under spatial cross-validation, the paradigms differ by less than 6 % in RMSE, while their per-fit cost differs by an order of magnitude. Adding a station-type covariate to a combined-station training set removes the systematic 4 µg/m³ underprediction at road-side monitors regardless of paradigm. The accompanying aqsurface R package, released alongside this article, implements the comparison as a single benchmark function that returns RMSE, bias, and per-fit time in one tibble.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>spatial interpolation, kriging, generalised additive model, air quality, cross-validation, reproducibility</p>
  </div>
</div>

</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<section id="air-pollution-and-population-exposure-in-seoul" class="level2">
<h2 class="anchored" data-anchor-id="air-pollution-and-population-exposure-in-seoul">Air pollution and population exposure in Seoul</h2>
<p>Population health has been seriously threatened by daily ambient air pollution in South Korea. Despite the efforts to legislate national pollution standards, daily peaks in recent winters and springs have already exceeded the standards countless times. During 5-8 March 2019, the entire country experienced over 200 µg/m³ of PM<sub>10</sub> and smog episodes; the national authorities warned everyone to reduce outdoor activities. As most of Seoul’s areas tend to experience disastrous levels of pollution frequently, residents can be exposed to air pollution unconsciously, which in the long term can lead to respiratory or cardiovascular ailments <span class="citation" data-cites="Zhang2013">(<a href="#ref-Zhang2013" role="doc-biblioref">K. Zhang &amp; Batterman, 2013</a>)</span>. Thus, understanding the spatial and temporal aspects of air pollution and its relationship with exposure is crucial.</p>
<p>Exposure research has exploited spatial interpolation (SI) to investigate the relationship between ambient air pollution and population exposure in a spatial context, namely “which places have high air pollution?” and “how many people can potentially become unwell from high episodes?” <span class="citation" data-cites="Jerrett2005 Hoek2008 LimLee2024">(<a href="#ref-Hoek2008" role="doc-biblioref">Hoek et al., 2008</a>; <a href="#ref-Jerrett2005" role="doc-biblioref">Jerrett et al., 2005</a>; <a href="#ref-LimLee2024" role="doc-biblioref">Lim &amp; Lee, 2024</a>)</span>. SI is a statistical method that can compute pollution fields over a wide area with a given set of point measurements. SI can mainly be split into a group that follows the assumption of spatial autocorrelation (e.g.&nbsp;Inverse Distance Weighted (IDW), kriging) and a group on statistical inference such as generalised linear models and generalised additive models <span class="citation" data-cites="Wood2017">(<a href="#ref-Wood2017" role="doc-biblioref">Wood, 2017</a>)</span>. Methods that take spatial autocorrelation into account assume that the values tend to be more similar when closer together, whereas methods that use statistical inference delineate the inferential surfaces over a region by minimising the residuals of the model. A third group, machine learning (e.g.&nbsp;random forests, <span class="citation" data-cites="Wright2017">(<a href="#ref-Wright2017" role="doc-biblioref">Wright &amp; Ziegler, 2017</a>)</span>), treats coordinates and station-level covariates as features without imposing any spatial structure a priori.</p>
<p>However, when air pollution monitoring stations such as those in Seoul are small in number compared to the size of the city, the estimation of the potential population at risk due to air pollution can be completely different depending on the measurement method used <span class="citation" data-cites="Wu2019">(<a href="#ref-Wu2019" role="doc-biblioref">Wu et al., 2019</a>)</span>. Wong, Yuan and Perlin <span class="citation" data-cites="Wong2004">(<a href="#ref-Wong2004" role="doc-biblioref">2004</a>)</span> used four spatial interpolation methods (spatial averaging, nearest neighbour, IDW, and kriging) to estimate children’s exposure to air pollution across the USA. The outcomes of the four methods only showed a small difference of PM10 and O3 where the monitoring stations were denser, for example in the north-eastern cities and urban California, but were difficult to predict in the mountainous regions and high-altitude zones. Aalto et al. <span class="citation" data-cites="Aalto2013">(<a href="#ref-Aalto2013" role="doc-biblioref">2013</a>)</span> compared a Generalised Additive Model (GAM) and ordinary kriging (OK) to predict monthly mean temperature and precipitation in Finland and found that the GAM outperformed other methods by a small amount, but the biased distribution of stations (“concentrated in the urban areas” of Finland) might have evened out the RMSE measures.</p>
<p>In addition, previous studies have provided tentative estimates of population risk based on annual or monthly statistics, but the aggregated figure lacks the potential for including acute injuries after an abrupt pollution rise, which may be more severe in their health consequences. Short-term ambient PM2.5 exposure is associated with a 0.67% increase in all-cause mortality among older adults per 10 µg/m³ over 2-day windows <span class="citation" data-cites="Di2017">(<a href="#ref-Di2017" role="doc-biblioref">Di et al., 2017</a>)</span>, and the multi-city analysis of Liu et al. <span class="citation" data-cites="Liu2024">(<a href="#ref-Liu2024" role="doc-biblioref">2024</a>)</span> across 380 urban areas confirms substantial temporal heterogeneity in the short-term effect that an annual mean would average out. The statistical machinery linking SI choices to this temporal axis has been described by Goldman et al. <span class="citation" data-cites="Goldman2011">(<a href="#ref-Goldman2011" role="doc-biblioref">2011</a>)</span>, where the spatial misalignment between sparse monitoring stations and dense population locations interacts with the temporal aggregation window to bias short-term effect estimates. There is likely to be a greater difference between methods when the population at risk is measured at a finer temporal scale, which is exactly the regime in which short-term exposure surveillance must operate.</p>
<p>This article aims to compare spatial interpolation methods that can support estimating population exposure to daily air pollution in Seoul. The study compares Universal Kriging (UK, geostatistics), Generalised Additive Models (GAM, statistical inference), and Random Forest (RF, machine learning) at the day-night scale (12 h mean), and examines whether explicit station-type covariates can remove the systematic bias between background and road-side monitors. The study also argues that the choice of validation strategy may matter more than the choice of algorithm, and that wall-clock cost per fit appears to be the dimension on which the three paradigms truly separate.</p>
</section>
<section id="a-three-paradigm-framing-of-the-literature" class="level2">
<h2 class="anchored" data-anchor-id="a-three-paradigm-framing-of-the-literature">A three-paradigm framing of the literature</h2>
<p>Empirical comparisons of spatial interpolation methods for urban air quality have multiplied since Wong et al. <span class="citation" data-cites="Wong2004">(<a href="#ref-Wong2004" role="doc-biblioref">2004</a>)</span> introduced inverse distance weighting, ordinary kriging and the nearest-neighbour method to a PM10 and O3 study of the United States monitoring network. The literature surveyed in <a href="#tbl-lit" class="quarto-xref">Table&nbsp;1</a> is broadly consistent in that no single method is uniformly best, and the relative ranking tends to vary with station density, study extent and the choice of error metric <span class="citation" data-cites="Aalto2013 Parmentier2014 Zhang2015">(<a href="#ref-Aalto2013" role="doc-biblioref">Aalto et al., 2013</a>; <a href="#ref-Parmentier2014" role="doc-biblioref">Parmentier et al., 2014</a>; <a href="#ref-Zhang2015" role="doc-biblioref">L. Zhang &amp; Shen, 2015</a>)</span>. However, each new study still reports a leaderboard in which one method is declared the winner on the basis of leave-one-out or in-sample root-mean-square error (RMSE), and the corresponding R package implementations rarely accompany the publication.</p>
<p>The modelling literature on urban air quality interpolation can be organised into three distinct paradigms that are rarely compared head to head. The first is geostatistics, exemplified by universal kriging in <code>gstat</code> <span class="citation" data-cites="Pebesma2004">(<a href="#ref-Pebesma2004" role="doc-biblioref">Pebesma, 2004</a>)</span>, which assumes a covariance structure tied to spatial separation and predicts via the best linear unbiased combination of observations. The second is statistical inference, exemplified by generalised additive models in <code>mgcv</code> <span class="citation" data-cites="Wood2017">(<a href="#ref-Wood2017" role="doc-biblioref">Wood, 2017</a>)</span>, which makes no covariance assumption and fits a smooth (typically thin-plate) regression surface with REML-selected smoothing parameters. The third is machine learning, exemplified by random forests in <code>ranger</code> <span class="citation" data-cites="Wright2017">(<a href="#ref-Wright2017" role="doc-biblioref">Wright &amp; Ziegler, 2017</a>)</span>, which treats coordinates and station-level covariates as features for an ensemble of regression trees and does not impose any spatial structure a priori.</p>
<p>Within-paradigm comparisons are abundant, but cross-paradigm comparisons that fix the data, the validation regime, and the software environment are not. Where they do exist, they tend to evaluate prediction accuracy alone, while the wall-clock cost of fitting is rarely reported. For practitioners, however, this can be the wrong question, since a method that is fractionally more accurate but considerably slower may not be preferable when the analysis must scan across 5 months by 3 decades by 20 daily columns by 2 pollutants, as in the present Seoul case study (approximately 1200 fit-and-predict invocations).</p>
<p>In addition, two methodological choices that are made before the paradigm selection appear to matter at least as much. With respect to validation strategy, in-sample RMSE for universal kriging on a constant trend collapses to numerical zero because kriging exactly interpolates its observations, so any comparison against a smoothing method may be structurally biased. With respect to covariate inclusion, when a study trains exclusively on background monitors and validates at road-side monitors, all three paradigms tend to underestimate the road-side concentration by several µg/m³, and this systematic bias can be closed by adding a single station-type factor as a covariate, regardless of paradigm.</p>
<p>The contribution of this article can therefore be summarised in three parts: a three-paradigm reframing of the comparison literature, a joint speed-accuracy benchmark across PM10 and NO2 on the Seoul network, and the aqsurface R package that operationalises the benchmark in one function call. The empirical work uses a 76-station Seoul monitoring network with one representative algorithm per paradigm: universal kriging (geostatistics), thin-plate-spline GAM (statistical inference), and random forest (machine learning). The aqsurface R package, released as the companion to this article (version 0.0.1, MIT-licensed, repository at <a href="https://github.com/dataandcrowd/aqsurface" class="uri">https://github.com/dataandcrowd/aqsurface</a>), implements the benchmark as a one-call function <code>benchmark_methods()</code> that returns a long-format tibble keyed by (algorithm, strategy, target) and carries both <code>rmse</code> and <code>time_s</code>. The package is currently in the “experimental” lifecycle stage and has not yet been submitted to CRAN. Readers can install the development version with <code>remotes::install_github("dataandcrowd/aqsurface")</code> and reproduce every table and figure in this article by sourcing <code>paper/figures.R</code>.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-lit" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Comparative spatial interpolation studies and validation choices.
</figcaption>
<div aria-describedby="tbl-lit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 26%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 18%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Authors</th>
<th style="text-align: left;">Region</th>
<th style="text-align: left;">Pollutant</th>
<th style="text-align: left;">N</th>
<th style="text-align: left;">Methods</th>
<th style="text-align: left;">Validation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Wong et al.&nbsp;(2004)</td>
<td style="text-align: left;">USA</td>
<td style="text-align: left;">PM<sub>10</sub>, O<sub>3</sub></td>
<td style="text-align: left;">732/739</td>
<td style="text-align: left;">IDW, OK, NN</td>
<td style="text-align: left;">LOOCV (R²)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Deligiorgi &amp; Philippopoulos (2011)</td>
<td style="text-align: left;">Athens</td>
<td style="text-align: left;">NO<sub>2</sub>, O<sub>3</sub></td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">IDW, OK, NN, ANN</td>
<td style="text-align: left;">LOOCV (MAE)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aalto et al.&nbsp;(2013)</td>
<td style="text-align: left;">Finland</td>
<td style="text-align: left;">Temp, precip</td>
<td style="text-align: left;">207/20</td>
<td style="text-align: left;">KED, GAM, GK</td>
<td style="text-align: left;">RMSE, MAD</td>
</tr>
<tr class="even">
<td style="text-align: left;">Parmentier et al.&nbsp;(2014)</td>
<td style="text-align: left;">Oregon, USA</td>
<td style="text-align: left;">Temperature</td>
<td style="text-align: left;">200-300</td>
<td style="text-align: left;">UK, GWR, GAM</td>
<td style="text-align: left;">RMSE, MAE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zhang &amp; Shen (2015)</td>
<td style="text-align: left;">Xi’an, China</td>
<td style="text-align: left;">PM2.5</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">IDW, OK, Trend surfaces</td>
<td style="text-align: left;">ME, MAE, RMSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">This study</td>
<td style="text-align: left;">Seoul, S. Korea</td>
<td style="text-align: left;">PM10, NO2</td>
<td style="text-align: left;">76</td>
<td style="text-align: left;">UK, GAM, RF</td>
<td style="text-align: left;">in-sample / spatial CV / held-out</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<p>The case study uses the Seoul Metropolitan Air Quality Monitoring Network operated by the Korea Environment Corporation (KECO). 76 fixed-position monitors are located within a 10 km buffer of the Seoul administrative boundary, of which 57 are designated as background sites and 19 as road-side sites. PM10 concentrations are recorded hourly (in µg/m³) and aggregated into day (08:00-19:00) and night (20:00-07:00) means. The analysis presented here uses ten consecutive days in January 2014 (decade S1) for the headline result.</p>
<p>Station coordinates use the Korea Central Belt 2000 / Mean Sea Level Bessel projection (EPSG:5181). Per-station covariates provided by KECO include Road_Dist (the distance to the nearest road, in metres) and DEM (the elevation, in metres). The contrast between the dense urban core and the surrounding mountainous fringe can be observed clearly, and is one of the reasons why the legacy validation strategy (training on background stations and validating at road-side stations) tends to produce a structural bias. <a href="#fig-stations" class="quarto-xref">Figure&nbsp;1</a> shows the station layout.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-stations" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="aqsurface-rjournal_files/figure-html/fig-stations-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Seoul air quality monitoring stations: 57 background (Fixed) and 19 road-side monitors used in this study, overlaid on the Seoul administrative boundary (simplified). The Han River corridor and the mountainous fringe to the north of the city are both visible as gaps in the monitor coverage.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<section id="geostatistics-universal-kriging" class="level2">
<h2 class="anchored" data-anchor-id="geostatistics-universal-kriging">Geostatistics: Universal Kriging</h2>
<p>Kriging is a geostatistical method that interpolates an unknown location using the characterised mean and variance structures <span class="citation" data-cites="Kumar2007 Kim2014">(<a href="#ref-Kim2014" role="doc-biblioref">Kim et al., 2014</a>; <a href="#ref-Kumar2007" role="doc-biblioref">Kumar, 2007</a>)</span>. It assumes that the overall mean, distance, and variance of all observations are spatially autocorrelated from Tobler’s First Law of Geography, namely that “everything is related to everything else, but nearer things are more related than distant things”. For example, pollution concentrations that are less than 1 metre apart are likely to be similar, but less likely to be similar when the distance becomes larger. To create a kriged map, three steps are required: (i) modelling an empirical semivariogram, (ii) fitting the empirical model with a mathematical model, and (iii) choosing the type of kriging according to the assumptions about the data (normality, stationarity, and the presence of trends).</p>
<p>The empirical semivariogram <span class="math inline">\(\hat{\gamma}(h)\)</span> at lag <span class="math inline">\(h\)</span> is the half-mean-squared difference between observations separated by that distance. In practice, pairs are binned by distance (ten bins to a 30 km cutoff are used in this study), the mean variance per bin is taken, and an asymptotic theoretical curve (the model semivariogram) is fitted by least squares. From this curve, three parameters can be derived: the nugget (the variance at lag zero, capturing measurement error and sub-sample-spacing variation), the partial sill (the asymptote minus the nugget), and the range (the lag at which the semivariogram levels off).</p>
<p>Variogram fitting is harder than its routine treatment in the literature would suggest. Three issues recur in the Seoul network. First, the 57 background stations occupy approximately 40 km by 30 km but are not uniformly distributed: more than half of them are clustered in central Seoul, while the surrounding districts are sparse. The sparsity tends to inflate uncertainty in long-lag bins, and unexpected outliers such as mountain ridges between station pairs may contradict the autocorrelation assumption. Second, theoretical semivariograms come in many families (spherical, circular, Gaussian, exponential, Stein-Matern, and so on), and the choice is largely empirical; the automatic fit is not always reliable. Third, the user has to constrain the spatial lag: too short a lag misses long-range variability, while too long a lag includes pairs that are no longer autocorrelated. A 30 km lag is used throughout this study. A pure-nugget fit, finally, can yield a bull’s-eye map (overfitting on local stations), while a flat fit can yield a smooth, contour-less map (underfitting). The function <code>fit_uk()</code> in aqsurface defaults to a Stein-Matern model, falls back to a spherical model with sensible starting values when that fit fails, and finally to a pure-nugget model so that downstream code is guaranteed an output.</p>
<p>For prediction, this article uses <strong>Universal Kriging</strong> (UK), a generalisation that allows a deterministic trend in the mean (e.g. a covariate such as <code>station_type</code>) and removes the stationarity assumption of Ordinary Kriging. UK is mathematically equivalent to Kriging with External Drift <span class="citation" data-cites="Aalto2013">(<a href="#ref-Aalto2013" role="doc-biblioref">Aalto et al., 2013</a>)</span>.</p>
</section>
<section id="statistical-inference-generalised-additive-models" class="level2">
<h2 class="anchored" data-anchor-id="statistical-inference-generalised-additive-models">Statistical inference: Generalised Additive Models</h2>
<p>The Generalised Linear Model (GLM) and the Generalised Additive Model (GAM) are regression methods that predict a response variable <span class="math inline">\(Y\)</span> based on explanatory variables <span class="math inline">\(X\)</span>. Compared to GLM, GAM uses combinations of linear and non-linear smoothings of explanatory variables to predict response variables, and is therefore a semi-parametric model in which the assumptions are generous and the relationships between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> can be non-linear <span class="citation" data-cites="Wood2017">(<a href="#ref-Wood2017" role="doc-biblioref">Wood, 2017</a>)</span>. For the application in this study, the response (PM10 or NO2 concentration) is modelled as a smooth function of the spatial coordinates,</p>
<p><span class="math display">\[
y_i = \beta_0 + s(X_i, Y_i) + \mathbf{x}_i^\top \boldsymbol{\beta}
       + \varepsilon_i,
\]</span></p>
<p>where <span class="math inline">\(s(X, Y)\)</span> is a thin-plate spline and <span class="math inline">\(\mathbf{x}_i\)</span> collects optional parametric covariates such as <code>station_type</code>, <code>Road_Dist</code> or <code>DEM</code>. The smoothing parameter is selected by restricted maximum likelihood (REML), which is the modern default in <code>mgcv</code> and tends to be more stable than ML on small networks.</p>
<p>GAM does not impose the spatial-autocorrelation assumption that kriging requires, but instead minimises the residuals of the penalised regression directly. As Wood <span class="citation" data-cites="Wood2017">(<a href="#ref-Wood2017" role="doc-biblioref">2017</a>)</span> notes, GAM’s <span class="math inline">\(p\)</span>-values are conditional on the smoothing penalty and should be interpreted with care; the robustness of the model can be better diagnosed by the estimated degrees of freedom (edf), the deviance explained, and visual inspection of partial-effect plots.</p>
</section>
<section id="machine-learning-random-forest" class="level2">
<h2 class="anchored" data-anchor-id="machine-learning-random-forest">Machine learning: Random Forest</h2>
<p>A random forest <span class="citation" data-cites="Wright2017">(<a href="#ref-Wright2017" role="doc-biblioref">Wright &amp; Ziegler, 2017</a>)</span> is an ensemble of regression trees that treats the spatial coordinates and any covariates as features, without imposing a spatial covariance structure a priori. Each tree is fit to a bootstrap resample of the training data using a random subset of features at each split, and the ensemble prediction is the mean across the trees. In this study <code>ranger::ranger()</code> is used with 500 trees and the default <code>respect.unordered.factors = "order"</code> setting, which is appropriate for the small two-level <code>station_type</code> factor.</p>
<p>RF carries no spatial-autocorrelation assumption and no smoothing penalty, and its inductive bias comes entirely from the bagging and splitting procedure. When coupled with covariates such as <code>Road_Dist</code> or <code>DEM</code>, RF can capture non-additive interactions between location and station type, which kriging and additive GAMs typically cannot.</p>
</section>
<section id="road-side-adjustment-via-an-empirical-ratio" class="level2">
<h2 class="anchored" data-anchor-id="road-side-adjustment-via-an-empirical-ratio">Road-side adjustment via an empirical ratio</h2>
<p>The legacy analysis of this network introduced a post-processing step that the present article retains for historical compatibility and exposes as the function <code>apply_road_ratio()</code>. After fitting the spatial surface on the 57 background monitors, road pixels (and highway pixels separately) are multiplied by an empirical Back-to-Road ratio computed from the per-day means of the 19 road-side monitors:</p>
<p><span class="math display">\[
r_t^{\text{road}} \;=\; \frac{\overline{C_t^{\text{road}}}}{\overline{C_t^{\text{back}}}},
\qquad
\widehat{C}_{x,t}^{\text{adjusted}} \;=\;
\widehat{C}_{x,t} \cdot \begin{cases}
   r_t^{\text{road}} &amp; \text{if } x \in \text{road pixels},\\
   r_t^{\text{high}} &amp; \text{if } x \in \text{highway pixels},\\
   1 &amp; \text{otherwise}.
\end{cases}
\]</span></p>
<p>This is a heuristic correction. It assumes that the multiplicative relationship between background and road-side concentrations is constant across the network, which is not necessarily the case: the ratio at a road in central Seoul tends to be much higher than at a road in the suburbs even on the same day. The covariate approach taken later in this article (training all paradigms on the combined network with <code>station_type</code> as a factor) can supersede the ratio approach in two respects. First, it allows each paradigm to learn the spatial gradient between the two populations rather than imposing a global multiplier. Second, it generalises to additional covariates such as the distance to the nearest road, elevation, or traffic counts, which the ratio formulation cannot accommodate. <code>apply_road_ratio()</code> is retained because it can be a useful baseline and because it makes the connection to the legacy literature explicit, but the covariate path is recommended for new work.</p>
</section>
<section id="three-validation-strategies" class="level2">
<h2 class="anchored" data-anchor-id="three-validation-strategies">Three validation strategies</h2>
<p>A held-out set is a subset of the data that the model never sees during fitting and is used solely to estimate prediction error. It can be contrasted with two other regimes that often appear in the literature: in-sample evaluation, where the same observations are used for both training and testing, and cross-validation, where each observation is held out from the fit in exactly one fold and used for fitting in the rest. The three regimes differ in the strength of the generalisation claim they support: in-sample evaluation tends to underestimate the error, since the model has already seen the answer; CV estimates the error on unseen locations from the same population; and a held-out set drawn from a distinct sub-population tests extrapolation beyond the training distribution. All three are used in this study:</p>
<ol type="1">
<li>In-sample. Predictions are extracted at the same locations used to fit the model. UK with a constant trend interpolates exactly, so its in-sample RMSE is essentially zero by construction.</li>
<li>Spatial cross-validation. The training set is partitioned into five spatially compact folds via k-means clustering on the coordinates <span class="citation" data-cites="Roberts2017 Meyer2018">(<a href="#ref-Meyer2018" role="doc-biblioref">Meyer et al., 2018</a>; <a href="#ref-Roberts2017" role="doc-biblioref">Roberts et al., 2017</a>)</span>. Each fold is held out in turn while the model is fit on the remaining four. This controls for the spatial autocorrelation that random k-fold CV would leak. When <code>station_type</code> is used as a covariate, the partition is stratified so that every fold contains both levels; without stratification, UK can return a rank-deficient kriging system on some folds.</li>
<li>Held-out validation against road-side monitors. When training is restricted to the 57 background monitors, the 19 road-side monitors form a permanent held-out set, since none of these road-side observations are used in fitting. The resulting RMSE measures the model’s ability to extrapolate from the background sub-population to the road-side sub-population. This regime is the strongest of the three, and is the one practitioners actually need when the operational task is to estimate road-side exposure from a background-only network. The term “held-out” is preferred here over “test set” or “out-of-sample” because the latter terms can conflate distribution-shift extrapolation (which is tested here) with within-distribution interpolation (which spatial CV tests).</li>
</ol>
<p>For each (paradigm, strategy, target column) combination, the following are recorded: <span class="math inline">\(n\)</span>, RMSE, MAE, bias, Pearson correlation, and the wall-clock time per fit. Bias is defined as the mean signed prediction error, <span class="math inline">\(\mathrm{bias} = \frac{1}{n} \sum_{i=1}^n (\hat{y}_i - y_i)\)</span>, so that a positive value indicates systematic over-prediction and a negative value systematic under-prediction. Distinguishing bias from RMSE matters in this study because RMSE captures the magnitude of error without sign, and two methods can therefore have identical RMSE while one systematically over-predicts and the other systematically under-predicts. The 4 µg/m³ road-side under-estimation reported below is a bias finding rather than an RMSE finding, since the spatial-CV RMSE for all three paradigms remains around 10 µg/m³ regardless of whether <code>station_type</code> is included. Per-fold cross-validation timings are averaged so that the time column is comparable across strategies.</p>
</section>
</section>
<section id="the-aqsurface-package" class="level1">
<h1>The aqsurface package</h1>
<p>aqsurface is a self-contained reproducible companion to this article. The user-facing API consists of three layers:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Ingestion</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">read_pollutant_rdata</span>(); <span class="fu">load_pollutant</span>(); <span class="fu">make_station_sf</span>()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Modelling primitives</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">fit_uk</span>();  <span class="fu">predict_uk</span>()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">fit_gam</span>(); <span class="fu">predict_gam</span>()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">fit_rf</span>();  <span class="fu">predict_rf</span>()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Composition</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">combine_stations</span>(); <span class="fu">spatial_kmeans_folds</span>(<span class="at">stratify_by =</span> ...)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">benchmark_methods</span>(train, holdout, targets, algorithms,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">covariates =</span> <span class="cn">NULL</span>, <span class="at">stratify_by =</span> <span class="cn">NULL</span>, ...)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Legacy post-processing (kept for historical compatibility)</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">apply_road_ratio</span>(surface, road_raster, ratio); <span class="fu">tidy_ratio_table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The package targets sf and terra throughout, dropping the legacy sp / rgdal / raster dependencies that have been retired from CRAN. A small Jan S1 demo bundle (~30 KB across four <code>.rda</code> files) ships with the package so the vignettes and examples run without the original 530 MB monitoring archive.</p>
<p>A typical user session reproduces the headline number in eight lines:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aqsurface); <span class="fu">library</span>(sf); <span class="fu">library</span>(dplyr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"pm10_jan_s1"</span>,      <span class="at">package =</span> <span class="st">"aqsurface"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"pm10_jan_s1_road"</span>, <span class="at">package =</span> <span class="st">"aqsurface"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>train   <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(pm10_jan_s1,      <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>), <span class="at">crs =</span> <span class="dv">5181</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>holdout <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(pm10_jan_s1_road, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"X"</span>,<span class="st">"Y"</span>), <span class="at">crs =</span> <span class="dv">5181</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>bm <span class="ot">&lt;-</span> <span class="fu">benchmark_methods</span>(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">train =</span> train, <span class="at">holdout =</span> holdout,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">targets =</span> <span class="fu">decade_columns</span>(<span class="st">"pm10"</span>, <span class="dv">1</span>, <span class="st">"S1"</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">algorithms =</span> <span class="fu">c</span>(<span class="st">"uk"</span>, <span class="st">"gam"</span>, <span class="st">"rf"</span>),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">cv_folds =</span> <span class="dv">5</span>, <span class="at">seed =</span> <span class="dv">1</span>, <span class="at">progress =</span> <span class="cn">FALSE</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(bm, target <span class="sc">==</span> <span class="st">"ALL"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(algorithm, strategy, rmse, bias, time_s)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 9 x 5</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   algorithm strategy    rmse   bias time_s</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 gam       held-out   11.2  -4.88   0.18</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 gam       in-sample   7.41  0.00   0.18</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 gam       spatial-cv 10.5  -0.72   0.19</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4 rf        held-out   11.2  -4.78   0.05</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5 rf        in-sample   4.58 -0.03   0.05</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6 rf        spatial-cv 10.0  -0.16   0.05</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7 uk        held-out   10.6  -4.13   0.45</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8 uk        in-sample   0.00  0.00   0.45</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9 uk        spatial-cv 10.5   0.01   0.46</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>aqsurface is released under the MIT licence; this article accompanies version 0.0.1, the <strong>experimental</strong> lifecycle stage. CRAN submission is planned after peer review of the present manuscript. R CMD check on macOS, Linux, and Windows × R-release / R-devel is automated via GitHub Actions and passes with zero errors, warnings, or notes at the time of writing.</p>
<section id="relation-to-existing-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="relation-to-existing-r-packages">Relation to existing R packages</h2>
<p>aqsurface does not introduce a new interpolation algorithm; it composes existing CRAN packages into a single benchmark abstraction. <a href="#tbl-pkgs" class="quarto-xref">Table&nbsp;2</a> shows where it fits in the ecosystem.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-pkgs" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pkgs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: aqsurface in the context of existing CRAN tooling. The first three rows are the algorithm engines this article wraps; the last two rows are the closest functional cousins, focused on machine-learning workflows and on raster-based interpolation respectively.
</figcaption>
<div aria-describedby="tbl-pkgs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 31%">
<col style="width: 64%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Package</th>
<th style="text-align: left;">Primary scope</th>
<th style="text-align: left;">What aqsurface adds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gstat</td>
<td style="text-align: left;">Geostatistics: variograms, kriging, simulation</td>
<td style="text-align: left;">Robust fallback chain; per-fit timing; uniform output for benchmarking</td>
</tr>
<tr class="even">
<td style="text-align: left;">mgcv</td>
<td style="text-align: left;">Statistical inference: GAMs, smoothing splines</td>
<td style="text-align: left;">Same; integrates with the same benchmark grammar</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ranger</td>
<td style="text-align: left;">Machine learning: random forests in C++ / R</td>
<td style="text-align: left;">Wraps as a third paradigm under one API</td>
</tr>
<tr class="even">
<td style="text-align: left;">CAST</td>
<td style="text-align: left;">Spatial CV folds and target-oriented validation</td>
<td style="text-align: left;">Built-in <code>spatial_kmeans_folds(stratify_by =)</code> covers the most common use case without CAST’s model-list overhead</td>
</tr>
<tr class="odd">
<td style="text-align: left;">intamap</td>
<td style="text-align: left;">Automatic interpolation pipeline (kriging family only)</td>
<td style="text-align: left;">Cross-paradigm comparison rather than within-paradigm autoselection</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The contribution is therefore a benchmarking <em>abstraction</em>, not a new interpolation method. Where existing packages provide single-paradigm depth, aqsurface provides cross-paradigm breadth plus a uniform speed-accuracy reporting layer.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="validation-strategy-a-three-way-decomposition" class="level2">
<h2 class="anchored" data-anchor-id="validation-strategy-a-three-way-decomposition">Validation strategy: a three-way decomposition</h2>
<p><a href="#tbl-strategy" class="quarto-xref">Table&nbsp;3</a> reproduces the headline finding. The sample sizes <span class="math inline">\(n\)</span> in the table reflect the strategy used: <span class="math inline">\(n = 1140\)</span> for in-sample and spatial-CV (57 background stations × 20 day-night target columns; each background station is predicted once at its own location for in-sample, and once across folds for spatial-CV), and <span class="math inline">\(n = 380\)</span> for held-out (19 road-side stations × 20 columns; the road-side stations are never used during training in the baseline scenario). Under the baseline scenario (background-only training, with no covariates), universal kriging in-sample reports an RMSE that is effectively zero (on the order of <span class="math inline">\(10^{-11}\)</span> µg/m³, and displayed as <code>0.000</code> in the rounded table), because the kriging system interpolates each training station exactly. The same model evaluated under spatial cross-validation reports an RMSE of 10.50 µg/m³, a difference of roughly ten orders of magnitude that an in-sample report would have hidden entirely. Once the road-side monitors are introduced as the held-out set, the RMSE only rises modestly to 10.56 µg/m³, but a bias of -4.13 µg/m³ appears (with GAM at -4.88 µg/m³).</p>
<div class="cell" data-layout-align="center">
<div id="tbl-strategy" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-strategy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Baseline scenario: background-only training, no covariates. The change in RMSE between in-sample and spatial-cv (UK) and the -4 µg/m³ bias against road-side monitors are both invisible to the legacy reporting convention.
</figcaption>
<div aria-describedby="tbl-strategy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">algorithm</th>
<th style="text-align: left;">strategy</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">rmse</th>
<th style="text-align: right;">bias</th>
<th style="text-align: right;">r</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gam</td>
<td style="text-align: left;">held-out</td>
<td style="text-align: right;">380</td>
<td style="text-align: right;">11.243</td>
<td style="text-align: right;">-4.883</td>
<td style="text-align: right;">0.937</td>
</tr>
<tr class="even">
<td style="text-align: left;">gam</td>
<td style="text-align: left;">in-sample</td>
<td style="text-align: right;">1140</td>
<td style="text-align: right;">7.407</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.968</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gam</td>
<td style="text-align: left;">spatial-cv</td>
<td style="text-align: right;">1140</td>
<td style="text-align: right;">10.518</td>
<td style="text-align: right;">-0.721</td>
<td style="text-align: right;">0.934</td>
</tr>
<tr class="even">
<td style="text-align: left;">rf</td>
<td style="text-align: left;">held-out</td>
<td style="text-align: right;">380</td>
<td style="text-align: right;">11.182</td>
<td style="text-align: right;">-4.777</td>
<td style="text-align: right;">0.936</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rf</td>
<td style="text-align: left;">in-sample</td>
<td style="text-align: right;">1140</td>
<td style="text-align: right;">4.582</td>
<td style="text-align: right;">-0.027</td>
<td style="text-align: right;">0.988</td>
</tr>
<tr class="even">
<td style="text-align: left;">rf</td>
<td style="text-align: left;">spatial-cv</td>
<td style="text-align: right;">1140</td>
<td style="text-align: right;">10.014</td>
<td style="text-align: right;">-0.161</td>
<td style="text-align: right;">0.940</td>
</tr>
<tr class="odd">
<td style="text-align: left;">uk</td>
<td style="text-align: left;">held-out</td>
<td style="text-align: right;">380</td>
<td style="text-align: right;">10.559</td>
<td style="text-align: right;">-4.130</td>
<td style="text-align: right;">0.941</td>
</tr>
<tr class="even">
<td style="text-align: left;">uk</td>
<td style="text-align: left;">in-sample</td>
<td style="text-align: right;">1140</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">uk</td>
<td style="text-align: left;">spatial-cv</td>
<td style="text-align: right;">1140</td>
<td style="text-align: right;">10.499</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">0.934</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The implication for the literature can be summarised as follows. The difference between in-sample and spatially cross-validated RMSE for UK spans roughly ten orders of magnitude, while the difference between UK and GAM under spatial CV is approximately zero.</p>
</section>
<section id="covariate-inclusion-eliminates-the-road-side-bias" class="level2">
<h2 class="anchored" data-anchor-id="covariate-inclusion-eliminates-the-road-side-bias">Covariate inclusion eliminates the road-side bias</h2>
<p><a href="#tbl-covariate" class="quarto-xref">Table&nbsp;4</a> reports the result of training all three algorithms on the combined 76-station network with <code>station_type</code> as a single two-level factor covariate. The held-out strategy is no longer applicable, since every monitor is now in the training set. Under spatial cross-validation (stratified so that both factor levels appear in every fold), the bias is brought to within ±0.6 µg/m³ for all three methods, an order-of-magnitude reduction from the baseline of approximately -4 µg/m³.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-covariate" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-covariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Combined-training + station_type covariate. The systematic -4 µg/m³ road-side bias reported in the baseline has been eliminated for all three methods; the RMSE differences between methods (10.0 to 10.6) are smaller than the reduction in bias.
</figcaption>
<div aria-describedby="tbl-covariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">algorithm</th>
<th style="text-align: left;">strategy</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">rmse</th>
<th style="text-align: right;">bias</th>
<th style="text-align: right;">r</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gam</td>
<td style="text-align: left;">in-sample</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">8.012</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.962</td>
</tr>
<tr class="even">
<td style="text-align: left;">gam</td>
<td style="text-align: left;">spatial-cv</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">10.615</td>
<td style="text-align: right;">-0.574</td>
<td style="text-align: right;">0.932</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rf</td>
<td style="text-align: left;">in-sample</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">6.602</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">0.974</td>
</tr>
<tr class="even">
<td style="text-align: left;">rf</td>
<td style="text-align: left;">spatial-cv</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">10.032</td>
<td style="text-align: right;">0.324</td>
<td style="text-align: right;">0.939</td>
</tr>
<tr class="odd">
<td style="text-align: left;">uk</td>
<td style="text-align: left;">in-sample</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">7.484</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.967</td>
</tr>
<tr class="even">
<td style="text-align: left;">uk</td>
<td style="text-align: left;">spatial-cv</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">10.428</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">0.934</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The qualitative implication remains unchanged: the choice of algorithm appears to contribute up to about 6% of the RMSE variation, while the choice of validation strategy and covariate set tends to contribute far more. Random forest is marginally best by RMSE in this scenario, which can be explained by its capacity to capture non-additive interactions between location and station type. However, the difference is well within the run-to-run variability that may be observed across decades and pollutants.</p>
</section>
<section id="speed-where-the-paradigms-separate" class="level2">
<h2 class="anchored" data-anchor-id="speed-where-the-paradigms-separate">Speed: where the paradigms separate</h2>
<p>The accuracy of the three paradigms appears statistically indistinguishable, but the computational cost does not. <a href="#fig-speed" class="quarto-xref">Figure&nbsp;2</a> reports the median per-fit wall-clock time on the Seoul January S1 decade, as measured by the <code>time_s</code> column returned by <code>benchmark_methods()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-speed" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-speed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="aqsurface-rjournal_files/figure-html/fig-speed-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-speed-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Median per-fit wall-clock time on the Seoul Jan S1 decade (log scale, seconds). Each bar is the median across 20 day-night target columns × 5 spatial-CV folds, by paradigm × scenario. Random forest is consistently fastest; universal kriging carries the variogram-fitting cost. Speed-up factors of 5-15× across paradigms persist regardless of whether <code>station_type</code> is included as a covariate.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In the pilot Jan S1 run, the per-fit cost ordering is consistently RF &lt; GAM &lt; UK, and UK can be 5-15 times slower than RF depending on the variogram family that wins the fallback chain. This matters operationally, since a five-month, two-pollutant scan over 30 decade windows by 20 daily columns by 3 algorithms by 5 folds amounts to approximately 9000 fit invocations. At RF’s typical 50 ms per fit, the scan completes in under ten minutes; at UK’s typical 500 ms per fit, the same scan can require approximately 75 minutes.</p>
<p>The accuracy results (<a href="#tbl-strategy" class="quarto-xref">Table&nbsp;3</a> and <a href="#tbl-covariate" class="quarto-xref">Table&nbsp;4</a>) show that the three paradigms agree to within 6% in RMSE under spatial CV, while the speed comparison shows that they can disagree by an order of magnitude. Where accuracy ties, speed may therefore become the decisive consideration.</p>
<p>The <code>time_s</code> column reports the cost of a single automatic fit, and in real workflows this can underestimate paradigm-specific overhead. Universal kriging requires the user to inspect each empirical variogram for stability, to choose a theoretical family (spherical, Gaussian, Stein-Matern), tune <code>cutoff</code>, <code>width</code>, and the nugget if the auto-fit collapses, and re-run on borderline days. We absorbed this work into <code>fit_uk()</code>’s tiered fallback chain, but the chain itself runs three fits per call in the worst case. The GAM analogue is checking the basis dimension <code>k</code>: a well-fit thin-plate spline reports an <code>edf</code> well below <code>k</code>, but small networks routinely fall on the wrong side of that test and require <code>k</code> to be increased and the model to be re-fitted. A practitioner who runs <code>gam.check()</code> on every target therefore adds a second fit-and-plot cycle that the <code>time_s</code> column does not see. RF has neither diagnostic. The 5-15 times wall-clock gap reported above is therefore a lower bound on the practical effort gap, and in the work that underlies the present article that gap was closer to a factor of two in person-hours, almost entirely on the kriging side.</p>
</section>
<section id="winter-and-summer-contrasting-two-atmospheric-regimes" class="level2">
<h2 class="anchored" data-anchor-id="winter-and-summer-contrasting-two-atmospheric-regimes">Winter and summer: contrasting two atmospheric regimes</h2>
<p>The 30-cell sweep (5 months × 3 decades × 2 pollutants) splits naturally into two seasons that exercise the algorithms in qualitatively different ways. <strong>Winter</strong> (December, January, February) in Seoul is dominated by heating emissions, occasional trans-boundary Asian dust events, and cold-air inversions that trap pollutants near the surface; PM10 is high (often &gt;100 µg/m³) and the spatial pattern is large-scale, with a band of elevated concentration across the city that the three paradigms can capture relatively easily. <strong>Summer</strong> (August, September) is the opposite regime: PM10 falls below 50 µg/m³ on most days, and NO2 is more sharply localised at road-side monitors because faster photochemistry breaks down NO2 at the urban scale, leaving the emission proxy (vehicle exhaust at the road) as the dominant signal. We therefore expect that (i) winter PM10 will look similar across paradigms, (ii) summer NO2 will produce the largest paradigm-on-paradigm differences because the local-emission gradient is closer to the limits of the spatial-resolution that 76 stations can support, and (iii) bias on the held-out road-side monitors will be more severe in summer NO2 than in any other (pollutant, season) cell.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-robustness" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-robustness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Spatial-CV summary across the full sweep, median RMSE / IQR / bias by paradigm × season × pollutant. The within-paradigm spread (rmse_iqr) across cells is consistently larger than the between-paradigm difference (rmse_med differences across rows within a season). The summer NO2 block typically shows the largest IQR, reflecting the photochemical breakdown that pushes the spatial signal towards the road-side limit of the network.
</figcaption>
<div aria-describedby="tbl-robustness-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">pollutant</th>
<th style="text-align: left;">season</th>
<th style="text-align: left;">algorithm</th>
<th style="text-align: right;">n_cells</th>
<th style="text-align: right;">rmse_med</th>
<th style="text-align: right;">rmse_iqr</th>
<th style="text-align: right;">bias_med</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NO2</td>
<td style="text-align: left;">summer</td>
<td style="text-align: left;">gam</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7.458</td>
<td style="text-align: right;">1.174</td>
<td style="text-align: right;">-0.012</td>
</tr>
<tr class="even">
<td style="text-align: left;">NO2</td>
<td style="text-align: left;">summer</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7.528</td>
<td style="text-align: right;">1.160</td>
<td style="text-align: right;">-0.186</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NO2</td>
<td style="text-align: left;">summer</td>
<td style="text-align: left;">uk</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7.487</td>
<td style="text-align: right;">1.253</td>
<td style="text-align: right;">-0.217</td>
</tr>
<tr class="even">
<td style="text-align: left;">NO2</td>
<td style="text-align: left;">winter</td>
<td style="text-align: left;">gam</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">8.459</td>
<td style="text-align: right;">1.341</td>
<td style="text-align: right;">0.386</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NO2</td>
<td style="text-align: left;">winter</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">8.293</td>
<td style="text-align: right;">0.773</td>
<td style="text-align: right;">-0.121</td>
</tr>
<tr class="even">
<td style="text-align: left;">NO2</td>
<td style="text-align: left;">winter</td>
<td style="text-align: left;">uk</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">8.233</td>
<td style="text-align: right;">0.963</td>
<td style="text-align: right;">-0.027</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PM10</td>
<td style="text-align: left;">summer</td>
<td style="text-align: left;">gam</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7.841</td>
<td style="text-align: right;">0.626</td>
<td style="text-align: right;">-1.676</td>
</tr>
<tr class="even">
<td style="text-align: left;">PM10</td>
<td style="text-align: left;">summer</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7.334</td>
<td style="text-align: right;">0.339</td>
<td style="text-align: right;">-0.895</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PM10</td>
<td style="text-align: left;">summer</td>
<td style="text-align: left;">uk</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7.462</td>
<td style="text-align: right;">0.342</td>
<td style="text-align: right;">-0.699</td>
</tr>
<tr class="even">
<td style="text-align: left;">PM10</td>
<td style="text-align: left;">winter</td>
<td style="text-align: left;">gam</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10.480</td>
<td style="text-align: right;">1.015</td>
<td style="text-align: right;">-1.043</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PM10</td>
<td style="text-align: left;">winter</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10.014</td>
<td style="text-align: right;">1.833</td>
<td style="text-align: right;">-0.411</td>
</tr>
<tr class="even">
<td style="text-align: left;">PM10</td>
<td style="text-align: left;">winter</td>
<td style="text-align: left;">uk</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10.499</td>
<td style="text-align: right;">1.486</td>
<td style="text-align: right;">-0.561</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The within-paradigm spread (interquartile range across cells) remains larger than the between-paradigm gap on the median in both seasons, confirming the Jan S1 conclusion at full scale: paradigm choice contributes much less to prediction error than seasonal variation in the underlying pollutant field. The <strong>summer NO2</strong> block in particular concentrates the variability that the algorithms cannot recover, consistent with photochemistry locating the dominant signal at the road-side rather than the regional scale.</p>
</section>
<section id="what-the-predicted-surfaces-actually-look-like" class="level2">
<h2 class="anchored" data-anchor-id="what-the-predicted-surfaces-actually-look-like">What the predicted surfaces actually look like</h2>
<p><a href="#fig-surfaces" class="quarto-xref">Figure&nbsp;3</a> shows the three predicted PM10 (and, when available, NO2) surfaces side by side on the highest-spatial-variance day of the Jan S1 decade for each pollutant. All paradigms are trained on the combined 76-station network with the same predictors (X, Y only); we use the spatial-only specification here because the prediction grid has no per-pixel <code>station_type</code> field. The qualitative agreement is the visual counterpart of the spatial-CV RMSE table: all three paradigms recover the same broad-scale structure and disagree mainly in fine detail. Contour lines on top of the colour fill make the iso-concentration bands directly comparable across paradigms; visible deformation of contours between panels signals where one paradigm’s smoothing assumptions break.</p>
<p>A noteworthy effect appears in the UK panel: on several representative days the kriging surface collapses to a near-flat field, with no contour bands at all. This is not a software defect but the geostatistical answer to a misspecified model. The combined Fixed + Road population has a bimodal pollutant distribution: with a constant or simple coordinate trend, the empirical variogram inherits enough between-class variance to mask the within-class spatial autocorrelation, and <code>fit_uk()</code>’s tiered fallback chain retreats to a near-nugget specification. Predictions under such a variogram reduce to the (trend-adjusted) global mean everywhere. The flattening is therefore <em>diagnostic</em>: it tells the analyst that the constant-trend kriging assumption has been violated and that the data demand a covariate. Re-running UK in the Step 2 covariate scenario (background-only training and no factor levels mixing in residuals) recovers a structured surface; the flat panels are the price of asking kriging to do something it was not designed to do.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-surfaces" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-surfaces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/surface_comparison.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-surfaces-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Predicted pollutant surfaces fit on the combined 76-station network with X and Y as the only predictors. Top row: PM10 (μg/m³) on January 7, night-time (station SD 15.4 μg/m³). Bottom row: NO₂ (ppb) on January 3, daytime (station SD 12.7 ppb). GAM produces a smooth field; random forest shows step-like discontinuities at decision-tree boundaries. Universal kriging here uses a constant + linear-coordinates trend on a heterogeneous Fixed + Road population; the variogram fitter sometimes retreats to the pure-nugget fallback in <code>fit_uk()</code> and the resulting surface flattens to the trend-adjusted mean. This flattening is itself diagnostic, indicating that UK requires an explicit <code>station_type</code> covariate (Section 4.2). Contour lines (grey, 8 levels) trace iso-concentration bands. Monitoring stations are overlaid in black (○ background, △ road-side); Seoul administrative boundary in grey.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The surfaces echo the per-station disagreement analysis below: the three paradigms are visually indistinguishable in the well-monitored city centre and visibly diverge near the mountainous fringes, where the kriging stationarity assumption is locally violated and the GAM smoothing penalty has the least training data to push against.</p>
</section>
<section id="where-the-paradigms-disagree-geographically" class="level2">
<h2 class="anchored" data-anchor-id="where-the-paradigms-disagree-geographically">Where the paradigms disagree geographically</h2>
<p>A station-level decomposition asks the complementary question, namely whether the three paradigms agree at the same places. <a href="#fig-disagreement" class="quarto-xref">Figure&nbsp;4</a> maps the per-station standard deviation of UK, GAM, and RF predictions, averaged across the 20 day-night target columns of the Jan S1 decade. A small SD at a station can be interpreted as paradigm agreement, while a large SD identifies a station where at least one paradigm departs from the others, typically because the station sits at a discontinuity in the spatial structure (a topographic barrier, a sudden land-use change, or an isolated emission source).</p>
<p>The largest disagreement appears along the <strong>western fringe</strong> of the metropolitan area, in the vicinity of the Gimpo airport and Gangseo, Yangcheon, and Magok districts, and along the <strong>north-western edge</strong> near Eunpyeong-gu. Several factors can plausibly contribute to this pattern. The western fringe is where the monitoring network thins out as the city gives way to the Han River corridor and the airport zone, so each paradigm extrapolates over relatively few neighbouring stations. The north-western edge is bounded by the Bukhansan ridge, which acts as a topographic barrier that violates the kriging stationarity assumption (the kriging variogram does not distinguish two stations on the same side of a ridge from two stations on opposite sides). By contrast, the dense urban core (Jongno-gu, Jung-gu, and the central commercial belt) shows tight paradigm agreement: the network density there is high enough that all three paradigms have similar information to work with.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-disagreement" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-disagreement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/paradigm_disagreement_map.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-disagreement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Per-station paradigm disagreement, measured as the standard deviation of UK / GAM / RF predictions averaged across the 20 day-night Jan S1 target columns. Stations with the largest disagreement (lighter colour) coincide with the mountainous fringes north and east of central Seoul; the dense urban core shows tight paradigm agreement. This is consistent with the Methods section’s argument that the kriging stationarity assumption breaks down across topographic barriers, but it is the place where modelled outputs are also least trustworthy regardless of paradigm.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The geographic finding is methodologically symmetric: the three paradigms agree where the underlying field is smooth (the city centre) and disagree where the field is morphologically complex (the mountainous edges). That symmetry is itself useful: it flags the stations whose predictions are weakest <em>regardless</em> of method, where the limit is in the data rather than in the algorithm choice.</p>
</section>
<section id="paradigm-rmse-distributions-full-sweep" class="level2">
<h2 class="anchored" data-anchor-id="paradigm-rmse-distributions-full-sweep">Paradigm RMSE distributions, full sweep</h2>
<p><a href="#fig-boxplot" class="quarto-xref">Figure&nbsp;5</a> complements <a href="#fig-speed" class="quarto-xref">Figure&nbsp;2</a> and <a href="#tbl-robustness" class="quarto-xref">Table&nbsp;5</a> with the underlying distributional view. The 30-cell × 20-target sweep on both pollutants makes paradigm-on-paradigm differences visually small relative to the spread of cell-to-cell variation.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-boxplot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/boxplot_paradigms.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Distribution of per-cell RMSE across the full PM10 and NO2 sweep (5 months × 3 decades × 20 day-night target columns) under spatial-CV and held-out evaluation. The within-paradigm spread (each box’s interquartile range) is consistently larger than the between-paradigm difference (gaps between boxes). The held-out facet for both pollutants is shifted upward, reflecting the structural bias against road-side monitors in the background-only training scenario.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="edge-case-pure-nugget-kriging-with-external-drift" class="level2">
<h2 class="anchored" data-anchor-id="edge-case-pure-nugget-kriging-with-external-drift">Edge case: pure-nugget kriging with external drift</h2>
<p>A by-product of robustness testing of the package is the observation that universal kriging with a pure-nugget variogram and an external drift formula produces a singular kriging system. This is a mathematical inevitability rather than a software defect: a zero-range variogram leaves no spatial information for the system to distribute among the drift coefficients. aqsurface handles the case transparently by falling back to ordinary least-squares trend prediction. We are not aware of this edge case being documented in the kriging-with-external-drift literature.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>This study set out to examine whether the choice of spatial interpolation method matters as much as it is commonly assumed to for daily PM10 and NO2 estimation across an urban monitoring network, and to quantify the practical cost of each method under a uniform benchmark. Three modelling paradigms (geostatistics, statistical inference, and machine learning) were compared on the Seoul Metropolitan Air Quality Monitoring Network using three validation strategies, two pollutants, and both speed and accuracy metrics. The aqsurface R package was developed to operationalise this comparison and to return RMSE, bias, and per-fit time in a single tibble indexed by (algorithm, strategy, target). The structural finding that emerged was that the strategy axis can dominate the algorithm axis under spatial cross-validation, and that the speed axis separates the paradigms once the accuracy axis ceases to.</p>
<p><strong>A precedent for the speed finding.</strong> The speed gap reported in <a href="#fig-speed" class="quarto-xref">Figure&nbsp;2</a> was already visible in the earlier analysis of this same Seoul network, where universal kriging required approximately 3-5 minutes per decade window while a thin-plate GAM finished in approximately 2 minutes. The gap was attributed at the time to the cost of empirical variogram fitting and to the rebuilding of the kriging system at every prediction location. That observation was recorded as a side note. In the present work, it has been formalised as a column in the output of <code>benchmark_methods()</code> and quantified across approximately 1200 fits in a controlled environment. Promoting wall-clock cost from an anecdote to a routinely reported metric can therefore be regarded as the principal contribution of the speed-axis reframing.</p>
<p><strong>Stationarity, transformations and edge cases.</strong> UK assumes second-order stationarity: a constant mean and a covariance that depends only on the lag between observations. In the Seoul network this assumption is locally violated. A canonical illustration involves the station pairs Jongno-Jung (both in the busy Seoul commercial centre) and Gyomun-Jungnang (separated by a 180 m-tall mountain ridge). The two pairs sit at similar separation distances and therefore enter the same variogram bin, yet the underlying covariance structures are entirely different: the first pair shares a single emission environment, the second is divided by a topographic barrier. The pure-nugget fallback in <code>fit_uk()</code> absorbs the worst consequences of this in our benchmark, but a formal solution requires barrier kriging <span class="citation" data-cites="Bakka2019">(<a href="#ref-Bakka2019" role="doc-biblioref">Bakka et al., 2019</a>)</span>, which has promising theoretical properties for cities with mountainous fringes but a heavy <code>INLA</code> dependency that we leave for future work.</p>
<p>A related consequence is that summer NO2 in the legacy analysis required a log-transformation before variogram fitting because the empirical distribution was strongly left-skewed. aqsurface does not auto-transform; users with this kind of data should either pass a transformed response or use the GAM / RF paradigm where Gaussianity is not required.</p>
<p>A second symptom of the same diagnostic shows up in <a href="#fig-surfaces" class="quarto-xref">Figure&nbsp;3</a> where one of the UK panels collapses to a near-flat field. When the training data mix two populations with substantially different means (here, background and road-side monitors) and no factor covariate is supplied, the empirical variogram absorbs the between-class variance into what looks like an inflated nugget; <code>fit_uk()</code>’s tiered fallback then retreats to the pure-nugget model and the kriged surface predicts a (trend-adjusted) constant everywhere. GAM and RF do not exhibit this failure mode because neither imposes a stationarity assumption on the residuals. The practical implication is that UK should be re-run with <code>station_type</code> (or any equivalent factor) entered explicitly as a covariate in <code>trend = ~ station_type</code>; in the Step 2 covariate scenario the kriging surface recovers structure and the spatial-CV RMSE remains within the same range as GAM and RF (<a href="#tbl-covariate" class="quarto-xref">Table&nbsp;4</a>). The flat panel is therefore not evidence against UK as a method but evidence that <em>constant-trend</em> UK is the wrong specification for a heterogeneous monitoring network.</p>
<p><strong>What the legacy validation methodology missed.</strong> A long-standing concern about the standard cross-validation indices used in spatial-interpolation papers (RMSE, MSE, MLE) is that they are confounded with overfitting: a kriging surface that exhibits the bull’s-eye pattern around training stations, and a GAM whose smoothing parameter has been tuned to chase residuals, both achieve good in-sample scores while producing maps that are demonstrably unreliable. The earlier qualitative version of this caveat made three concrete observations on the same Seoul network: (i) coercing the variogram nugget to zero produced visibly overfitted maps, with concentration peaks tightly localised at each training station and unrealistic gradients elsewhere; (ii) GAM with high <code>k</code> and weak penalty produced “wiggly” surfaces that looked attractive in-sample but failed on independent monitors; and (iii) statistical indices alone could not flag either failure mode because both increased their in-sample fit while making the underlying map less trustworthy.</p>
<p>The present work operationalises that caveat as the three-strategy decomposition reported in <a href="#tbl-strategy" class="quarto-xref">Table&nbsp;3</a>. UK’s in-sample RMSE of order <span class="math inline">\(10^{-11}\)</span> on a constant trend is the quantitative counterpart of the bull’s-eye intuition; the GAM in-sample versus spatial-CV gap (7.41 µg/m³ vs. 10.52 µg/m³) is the quantitative counterpart of the wiggliness intuition. Neither figure is visible to a leaderboard that reports a single in-sample RMSE column; both fall out naturally from the (algorithm × strategy) tibble that <code>benchmark_methods()</code> returns.</p>
<p><strong>Toward operational deployment.</strong> The natural next step is population-weighted exposure, which overlays the predicted surface with where people actually are and when. Several recent studies have proposed mobile-derived population fields for this purpose <span class="citation" data-cites="Dewulf2016 Nyhan2016 Xu2019">(<a href="#ref-Dewulf2016" role="doc-biblioref">Dewulf et al., 2016</a>; <a href="#ref-Nyhan2016" role="doc-biblioref">Nyhan et al., 2016</a>; <a href="#ref-Xu2019" role="doc-biblioref">Xu et al., 2019</a>)</span>; the aqsurface output (a multi-layer SpatRaster) is directly compatible with their downstream pipelines. The 12-hour day-night aggregation used in this article is a deliberate choice: it preserves the distinct daytime / night-time regimes (visible in the Seoul rush hour double-peak in NO2) without inheriting the noise of hourly data.</p>
<p><strong>Limitations.</strong> The 76-station Seoul network is dense by international standards, and sparser networks may show stronger inter-method differences because each method’s smoothing assumptions become more consequential when station spacing grows. The <code>station_type</code> factor used here is also a discrete proxy for an inherently continuous process, since the relationship between road-side concentration and distance to road is itself a function of traffic intensity, road width, and dispersion; a continuous covariate (e.g.&nbsp;log distance to the nearest major road) may close the bias gap further while preserving spatial extrapolation. Finally, the wall-clock measurements depend on hardware, parallelism, and the variogram family selected by the fallback chain in <code>fit_uk()</code> on any given day. The relative ordering across paradigms is reported rather than absolute numbers, but the absolute numbers can be recovered by re-running <code>paper/figures.R</code> on the reader’s machine.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>On the Seoul air quality network, the three modelling paradigms tested in this study (geostatistics, statistical inference, and machine learning) appear statistically indistinguishable in accuracy under spatial cross-validation, and two design decisions made before paradigm selection (validation strategy and covariate inclusion) explain more of the variance in reported performance than the paradigm itself. The three paradigms separate clearly in wall-clock cost per fit, where the difference can reach an order of magnitude. Future comparison studies are therefore encouraged to report spatial-CV accuracy together with per-fit time as a two-axis evaluation, and to ship the analysis code as an R package so that downstream readers can extend the comparison to their own networks. The aqsurface package operationalises both axes and the three-paradigm framing in a single function, <code>benchmark_methods()</code>, which returns <code>rmse</code> and <code>time_s</code> in one tibble.</p>
</section>
<section id="acknowledgements" class="level1 unnumbered">
<h1 class="unnumbered">Acknowledgements</h1>
<p>This work began as Chapter 3 of the first author’s PhD thesis at the University of Cambridge. The 60-script legacy code base that the aqsurface package replaces was written between 2018 and 2021 with sp, raster, and rgdal; the modernisation to sf and terra was completed during 2026 at the University of Auckland.</p>
</section>
<section id="software-and-code-availability" class="level1 unnumbered">
<h1 class="unnumbered">Software and code availability</h1>
<p>aqsurface is released as the companion software to this article. The development version (v0.0.1, lifecycle: experimental) is hosted at <a href="https://github.com/dataandcrowd/aqsurface" class="uri">https://github.com/dataandcrowd/aqsurface</a>. Submission to CRAN is planned subject to peer review of this manuscript. To reproduce the tables and figures locally, clone the repository, run the benchmark cache, then render the manuscript:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/dataandcrowd/aqsurface.git</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> aqsurface</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("devtools", "quarto", "ranger"))</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install</span>(<span class="st">"."</span>, <span class="at">build_vignettes =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"paper/figures.R"</span>)              <span class="co"># ~30 s on the demo bundle</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>quarto<span class="sc">::</span><span class="fu">quarto_render</span>(<span class="st">"paper/aqsurface-rjournal.qmd"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The full PM<sub>10</sub> and NO<sub>2</sub> benchmarks reported in <a href="#tbl-robustness" class="quarto-xref">Table&nbsp;5</a> require the legacy <code>pm10.RData</code> and <code>no2.RData</code> archives to be available locally; their path is read from the <code>AQSURFACE_DATA_DIR</code> environment variable (see <code>?aqs_data_dir</code>). The Jan S1 demo bundle that ships with the package is sufficient for every other table and figure in this article.</p>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Aalto2013" class="csl-entry" role="listitem">
Aalto, J., Pirinen, P., Heikkinen, J., &amp; Venäläinen, A. (2013). <span class="nocase">Spatial interpolation of monthly climate data for Finland: comparing the performance of kriging and generalized additive models</span>. <em>Theoretical and Applied Climatology</em>, <em>112</em>(1-2), 99–111. <a href="https://link.springer.com/article/10.1007/s00704-012-0716-9">https://link.springer.com/article/10.1007/s00704-012-0716-9</a>
</div>
<div id="ref-Bakka2019" class="csl-entry" role="listitem">
Bakka, H., Vanhatalo, J., Illian, J. B., Simpson, D., &amp; Rue, H. (2019). Non-stationary <span>Gaussian</span> models with physical barriers. <em>Spatial Statistics</em>, <em>29</em>, 268–288. <a href="https://doi.org/10.1016/j.spasta.2019.01.002">https://doi.org/10.1016/j.spasta.2019.01.002</a>
</div>
<div id="ref-Dewulf2016" class="csl-entry" role="listitem">
Dewulf, B., Neutens, T., Lefebvre, W., Seynaeve, G., Vanpoucke, C., Beckx, C., &amp; Van de Weghe, N. (2016). <span class="nocase">Dynamic assessment of exposure to air pollution using mobile phone data</span>. <em>International Journal of Health Geographics</em>, <em>15</em>(1), 1.
</div>
<div id="ref-Di2017" class="csl-entry" role="listitem">
Di, Q., Dai, L., Wang, Y., Zanobetti, A., Choirat, C., Schwartz, J. D., &amp; Dominici, F. (2017). Association of short-term exposure to air pollution with mortality in older adults. <em>JAMA</em>, <em>318</em>(24), 2446–2456. <a href="https://doi.org/10.1001/jama.2017.17923">https://doi.org/10.1001/jama.2017.17923</a>
</div>
<div id="ref-Goldman2011" class="csl-entry" role="listitem">
Goldman, G. T., Mulholland, J. A., Russell, A. G., Strickland, M. J., Klein, M., Waller, L. A., &amp; Tolbert, P. E. (2011). Spatial misalignment in time series studies of air pollution and health data. <em>Biostatistics</em>, <em>12</em>(4), 610–623. <a href="https://doi.org/10.1093/biostatistics/kxq068">https://doi.org/10.1093/biostatistics/kxq068</a>
</div>
<div id="ref-Hoek2008" class="csl-entry" role="listitem">
Hoek, G., Beelen, R., Hoogh, K. de, Vienneau, D., Gulliver, J., Fischer, P., &amp; Briggs, D. (2008). A review of land-use regression models to assess spatial variation of outdoor air pollution. <em>Atmospheric Environment</em>, <em>42</em>(33), 7561–7578. <a href="https://doi.org/10.1016/j.atmosenv.2008.05.057">https://doi.org/10.1016/j.atmosenv.2008.05.057</a>
</div>
<div id="ref-Jerrett2005" class="csl-entry" role="listitem">
Jerrett, M., Arain, A., Kanaroglou, P., Beckerman, B., Potoglou, D., Sahsuvaroglu, T., Morrison, J., &amp; Giovis, C. (2005). A review and evaluation of intraurban air pollution exposure models. <em>Journal of Exposure Science &amp; Environmental Epidemiology</em>, <em>15</em>(2), 185–204. <a href="https://doi.org/10.1038/sj.jea.7500388">https://doi.org/10.1038/sj.jea.7500388</a>
</div>
<div id="ref-Kim2014" class="csl-entry" role="listitem">
Kim, S.-Y., Yi, S.-J., Eum, Y. S., Choi, H.-J., Shin, H., Ryou, H. G., &amp; Kim, H. (2014). <span class="nocase">Ordinary kriging approach to predicting long-term particulate matter concentrations in seven major Korean cities</span>. <em>Environmental Health and Toxicology</em>, <em>29</em>, e2014012. <a href="https://doi.org/10.5620/eht.e2014012">https://doi.org/10.5620/eht.e2014012</a>
</div>
<div id="ref-Kumar2007" class="csl-entry" role="listitem">
Kumar, V. (2007). <span class="nocase">Optimal contour mapping of groundwater levels using universal kriging - A case study</span>. <em>Hydrological Sciences Journal</em>, <em>52</em>(5), 1038–1050. <a href="https://doi.org/10.1623/hysj.52.5.1038">https://doi.org/10.1623/hysj.52.5.1038</a>
</div>
<div id="ref-LimLee2024" class="csl-entry" role="listitem">
Lim, C. C., &amp; Lee, J.-S. (2024). A review of geospatial exposure models and approaches for health data integration. <em>Journal of Exposure Science &amp; Environmental Epidemiology</em>. <a href="https://doi.org/10.1038/s41370-024-00712-8">https://doi.org/10.1038/s41370-024-00712-8</a>
</div>
<div id="ref-Liu2024" class="csl-entry" role="listitem">
Liu, C., Chen, R., Cai, J., Niu, Y., Schwartz, J., Mortimer, K., Bell, M. L., Coelho, M. de S. Z. S., Saldiva, P. H. N., Sera, F., Vicedo-Cabrera, A. M., Gasparrini, A., &amp; Kan, H. (2024). Temporal variations in the short-term effects of ambient air pollution on cardiovascular and respiratory mortality: A pooled analysis of 380 urban areas over a 22-year period. <em>The Lancet Planetary Health</em>, <em>8</em>(9), e620–e632. <a href="https://doi.org/10.1016/S2542-5196(24)00168-2">https://doi.org/10.1016/S2542-5196(24)00168-2</a>
</div>
<div id="ref-Meyer2018" class="csl-entry" role="listitem">
Meyer, H., Reudenbach, C., Hengl, T., Katurji, M., &amp; Nauss, T. (2018). Improving performance of spatio-temporal machine learning models using forward feature selection and target-oriented validation. <em>Environmental Modelling &amp; Software</em>, <em>101</em>, 1–9. <a href="https://doi.org/10.1016/j.envsoft.2017.12.001">https://doi.org/10.1016/j.envsoft.2017.12.001</a>
</div>
<div id="ref-Nyhan2016" class="csl-entry" role="listitem">
Nyhan, M., Grauwin, S., Britter, R., Misstear, B., McNabola, A., Laden, F., Barrett, S. R. H., &amp; Ratti, C. (2016). <span class="nocase">"exposure track" - The impact of mobile-device-based mobility patterns on quantifying population exposure to air pollution</span>. <em>Environmental Science and Technology</em>, <em>50</em>(17), 9671–9681. <a href="https://doi.org/10.1021/acs.est.6b02385">https://doi.org/10.1021/acs.est.6b02385</a>
</div>
<div id="ref-Parmentier2014" class="csl-entry" role="listitem">
Parmentier, B., McGill, B., Wilson, A., Regetz, J., Jetz, W., Guralnick, R., Tuanmu, M.-N., Robinson, N., &amp; Schildhauer, M. (2014). <span class="nocase">An Assessment of Methods and Remote-Sensing Derived Covariates for Regional Predictions of 1 km Daily Maximum Air Temperature</span>. <em>Remote Sensing</em>, <em>6</em>(9), 8639–8670. <a href="https://doi.org/10.3390/rs6098639">https://doi.org/10.3390/rs6098639</a>
</div>
<div id="ref-Pebesma2004" class="csl-entry" role="listitem">
Pebesma, E. J. (2004). Multivariable geostatistics in <span>S</span>: The <span class="nocase">gstat</span> package. <em>Computers &amp; Geosciences</em>, <em>30</em>(7), 683–691. <a href="https://doi.org/10.1016/j.cageo.2004.03.012">https://doi.org/10.1016/j.cageo.2004.03.012</a>
</div>
<div id="ref-Roberts2017" class="csl-entry" role="listitem">
Roberts, D. R., Bahn, V., Ciuti, S., Boyce, M. S., Elith, J., Guillera-Arroita, G., Hauenstein, S., Lahoz-Monfort, J. J., Schröder, B., Thuiller, W., Warton, D. I., Wintle, B. A., Hartig, F., &amp; Dormann, C. F. (2017). Cross-validation strategies for data with temporal, spatial, hierarchical, or phylogenetic structure. <em>Ecography</em>, <em>40</em>(8), 913–929. <a href="https://doi.org/10.1111/ecog.02881">https://doi.org/10.1111/ecog.02881</a>
</div>
<div id="ref-Wong2004" class="csl-entry" role="listitem">
Wong, D. W., Yuan, L., &amp; Perlin, S. A. (2004). <span class="nocase">Comparison of spatial interpolation methods for the estimation of air quality data</span>. <em>Journal of Exposure Science &amp; Environmental Epidemiology</em>, <em>14</em>(5), 404–415. <a href="https://doi.org/10.1038/sj.jea.7500338">https://doi.org/10.1038/sj.jea.7500338</a>
</div>
<div id="ref-Wood2017" class="csl-entry" role="listitem">
Wood, S. N. (2017). <em><span class="nocase">Generalized additive models: an introduction with R</span></em>. Chapman; Hall/CRC.
</div>
<div id="ref-Wright2017" class="csl-entry" role="listitem">
Wright, M. N., &amp; Ziegler, A. (2017). <span class="nocase">ranger</span>: A fast implementation of random forests for high dimensional data in <span>C++</span> and <span>R</span>. <em>Journal of Statistical Software</em>, <em>77</em>(1), 1–17. <a href="https://doi.org/10.18637/jss.v077.i01">https://doi.org/10.18637/jss.v077.i01</a>
</div>
<div id="ref-Wu2019" class="csl-entry" role="listitem">
Wu, C.-Y., Mossa, J., Mao, L., &amp; Almulla, M. (2019). <span class="nocase">Comparison of different spatial interpolation methods for historical hydrographic data of the lowermost Mississippi River</span>. <em>Annals of GIS</em>, <em>25</em>(2), 133–151. <a href="https://doi.org/10.1080/19475683.2019.1588781">https://doi.org/10.1080/19475683.2019.1588781</a>
</div>
<div id="ref-Xu2019" class="csl-entry" role="listitem">
Xu, Y., Jiang, S., Li, R., Zhang, J., Zhao, J., Abbar, S., &amp; González, M. C. (2019). <span class="nocase">Unraveling environmental justice in ambient PM 2.5 exposure in Beijing: A big data approach</span>. <em>Computers, Environment and Urban Systems</em>, <em>75</em>(December 2018), 12–21. <a href="https://doi.org/10.1016/j.compenvurbsys.2018.12.006">https://doi.org/10.1016/j.compenvurbsys.2018.12.006</a>
</div>
<div id="ref-Zhang2013" class="csl-entry" role="listitem">
Zhang, K., &amp; Batterman, S. (2013). <span class="nocase">Air pollution and health risks due to vehicle traffic</span>. <em>Science of the Total Environment</em>, <em>450-451</em>, 307–316. <a href="https://doi.org/10.1016/j.scitotenv.2013.01.074">https://doi.org/10.1016/j.scitotenv.2013.01.074</a>
</div>
<div id="ref-Zhang2015" class="csl-entry" role="listitem">
Zhang, L., &amp; Shen, H. (2015). Comparison of three methods of spatial interpolation of <span>PM2.5</span> concentrations: A study of the <span class="nocase">Xi’an</span> metropolitan area, <span>China</span>. <em>Environmental Earth Sciences</em>, <em>73</em>(11), 7531–7540. <a href="https://doi.org/10.1007/s12665-014-3911-4">https://doi.org/10.1007/s12665-014-3911-4</a>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>